# Версия docker-compose
version: '3'
# Список наших сервисов (контейнеров)
services:
  php:
    # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
    build: ./images/php
    # монтируем директорию с проектами
    volumes:
      - ./www:/var/www
      - ./logs:/var/logs